let firstname: string = "HAMZA ";
let lastname: string = "SAJJAD ALI";
console.log(firstname + lastname);
let massage: string = "it is my first assignment after first calss basics";
console.log(massage);
let day: number = 19;
let month: string = " july";
let year: number = 2023;
console.log(day+' '+month+' '+year);
let lowercasename: string = firstname.toLowerCase();
let lower_casename: string = lastname.toLocaleLowerCase();
console.log(lowercasename+' '+lower_casename);
let upercasename: string = firstname.toLocaleUpperCase();
let uper_casename: string = lastname.toLocaleUpperCase();
console.log(upercasename+' '+uper_casename);
